### ISSUE TITLE
But should not happen in When section

### ISSUE THREAD

**Issue by phil-davis** [gherlint/gherlint#108]
## Steps to reproduce
Have a feature like:
```
Feature: some feature
  Scenario: a scenario to test the feature
    Given a user has been created
    When the user does something
    And the user does something else
    But the user does not upload the file
    Then the file should not exist
    And something else should be true
    But something else should be false
```

## Expected behavior
the scenario fails because of:
```
    But the user does not upload the file
```

## Actual behavior
this scenario passes

I can't think of a scenario where it is sensible to use "But" in a group of "When" steps.

Maybe there should be an optional rule, defaulting to on, which will report this - maybe call it `no_but_in_when_steps`

Similarly, it seems unusual to use "But" in the "Given" steps.
```
Given a user has been created
And a file has been uploaded
But the user has not logged in
```
But maybe there are scenarios where it is useful to say what has not happened in the scenario set up?
I am not so sure about this rule, but anyway, there could be an optional rule `no_but_in_given_steps`

**Comment by saw-jan** [comment]
`no_but_in_given_when` has been added
