### ISSUE TITLE
Lines with only whitespace are reported in DocStrings

### ISSUE THREAD

**Issue by phil-davis** [gherlint/gherlint#110]
## Describe the bug
A DocString might have empty lines in it. But those empty lines will have whitespace to the indent level of the DocString.
This fails gherlint.

## Steps to reproduce
```
    Then the content of file "/FOLDER/textfile.txt" for user "Alice" should be:
      """
      This is a testfile.
      
      Cheers.
      """
```
## Expected behavior
This should pass, as long as the whitespace is to the expected indent level.

## Actual behavior
```
$ npx gherlint --fix tests/acceptance/features

/home/phil/git/owncloud/core/tests/acceptance/features/apiShareOperationsToRoot2/uploadToShare.feature (1ms)
  error  55:1  No trailing whitespaces  no_trailing_whitespace
  error  81:1  No trailing whitespaces  no_trailing_whitespace
  error  103:1  No trailing whitespaces  no_trailing_whitespace
  error  127:1  No trailing whitespaces  no_trailing_whitespace
  error  149:1  No trailing whitespaces  no_trailing_whitespace
```

The fixer does not "fix" this, which is good!

There might be cases where someone wants to use a DocString that purposely has whitespace at the end of line(s). But that is a different issue. If someone wants that, then we would need to have an option for `no_trailing_whitespace` that allows trailing whitespace in DocStrings.

**Comment by saw-jan** [comment]
>There might be cases where someone wants to use a DocString that purposely has whitespace at the end of line(s). But that is a different issue. If someone wants that, then we would need to have an option for no_trailing_whitespace that allows trailing whitespace in DocStrings.

I would prefer `no_trailing_whitespace` rule to not touch the whitespaces in docstring block. here's the PR https://github.com/gherlint/gherlint/pull/116
