### ISSUE TITLE
Fix command freezes for long time

### ISSUE THREAD

**Issue by grgprarup** [gherlint/gherlint#77]
## Describe the bug
The command freezes without any message.

## Steps to reproduce
1. npx gherlint --fix features/

## Expected behavior
The command should be successful or display an error message and exit.

## Actual behavior
Stucked and no message
When checking from another terminal for issues using `npx gherlint features/`, shows less error. So, some of them are fixed.

## Version
`1.0.0-beta.2`
Node: 18.17.1

**Comment by saw-jan** [comment]
Could be due to large number of feature files or not-fixable lint problems

**Comment by grgprarup** [comment]
> Could be due to large number of feature files or not-fixable lint problems

For me, that might be due to a not-fixable or something like that. Because it was hanged for more than 20 mins.

For a large number of feature files, if the fix takes more than 5 min (just an e.g.) then it will be worse, so we have to think about optimization.

**Comment by saw-jan** [comment]
Looks like the problem was due to unnecessary multiple loops while applying the fix. Should be fixed in https://github.com/gherlint/gherlint/pull/78
