### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by saw-jan** [gherlint/gherlint#93]
### Release Blockers
- [x] https://github.com/gherlint/gherlint/issues/100
- [x] https://github.com/gherlint/gherlint/issues/105

### PRE-RELEASE
- [x] update [CHANGELOG.md](https://github.com/gherlint/gherlint/blob/main/CHANGELOG.md)
- [x] bump version to `1.0.0-rc.x`
  - `package.json`
  - `CHANGELOG.md`
- [x] check successful CI runs
- [x] create rc tag `v1.0.0-rc.x`
  - [x] successful CI run

**QA**
- [x] installation: `npm i @gherlint/gherlint`
- [x] check/Test available command options:
  - [x] `npx gherlint --help` - shows all available options
  - [x] `npx gherlint --version` - check version is correct
- [x] check different feature paths: `npx gherlint <path>`
  - [x] single file (`features/login.feature`)
  - [x] folder (`features`)
  - [x] glob pattern (`features/**/*.feature`)
- [x] check --fix option fixes the fixable lint problems 
  - [x] `npx gherlint --fix <path-to-feature-file>`
- [x] run linter on test feature file(s) - (create feature file(s) to check all available rules)
- [x] check config file can be used:
  - [x] `.gherlintrc`
  - [x] `.gherlintrc.json`
  - [x] `.gherlintrc.js`
  - [x] multiple config files in the project root - check for message
- [x] modify between different lint severity levels (`error`, `warn`, `off`) - check for respective lint reports

### RELEASE
- [x] update CHANGELOG.md (add changelog for fixes/patches if any)
- [x] bump version to `1.0.0`
  - `package.json`
  - `CHANGELOG.md`
- [x] create release tag `v1.0.0`
  - [x] successful CI run

**Comment by ishabaral** [comment]
Published (https://github.com/gherlint/gherlint/releases/tag/v1.0.0)
